name: exploring context

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  exploring:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Execute
        run: |
          echo '${{ toJSON(github) }}' > event.json
          ls -al ${{ github.workspace }}
          python scripts/tools.py